-- GearCheck :: Items.lua  (auto-generated from the guild BiS sheet)
-- GC.ITEM_BIS[profile][slot] = { [itemName]=true }  — accepted items per slot.
GearCheck = GearCheck or {}
local GC = GearCheck
GC.ITEM_BIS = {
  ["Agi Mail"] = {
    ["Back"] = { ["Shadowvault Slayer's Cloak"]=true },
    ["Chest"] = { ["Carapace of Forgotten Kings"]=true, ["Frost Witch's Chestguard"]=true, ["Sanctified Frost Witch's Chestguard"]=true },
    ["Feet"] = { ["Returning Footfalls"]=true },
    ["Hands"] = { ["Frost Witch's Grips"]=true, ["Sanctified Frost Witch's Grips"]=true },
    ["Head"] = { ["Frost Witch's Faceguard"]=true, ["Sanctified Frost Witch's Faceguard"]=true },
    ["Legs"] = { ["Frost Witch's War-Kilt"]=true, ["Sanctified Frost Witch's War-Kilt"]=true },
    ["Main Hand"] = { ["Havoc's Call, Blade of Lordaeron Kings"]=true },
    ["Neck"] = { ["Precious's Putrid Collar"]=true },
    ["Off Hand"] = { ["Havoc's Call, Blade of Lordaeron Kings"]=true },
    ["Ranged"] = { ["Totem of the Surging Sea"]=true },
    ["Ring"] = { ["Ashen Band of Endless Vengeance"]=true, ["Signet of Twilight"]=true },
    ["Shoulder"] = { ["Frost Witch's Shoulderguards"]=true, ["Sanctified Frost Witch's Shoulderguards"]=true },
    ["Trinket"] = { ["Deathbringer's Will"]=true, ["Sharpened Twilight Scale"]=true },
    ["Waist"] = { ["Nerub'ar Stalker's Cord"]=true },
    ["Wrist"] = { ["Scourge Hunter's Vambraces"]=true },
  },
  ["Cloth Caster — Crit"] = {
    ["Back"] = { ["Cloak of Burning Dusk"]=true },
    ["Chest"] = { ["Bloodmage Robe"]=true, ["Crimson Acolyte Raiments"]=true, ["Dark Coven Robe"]=true, ["Robe of the Waking Nightmare"]=true, ["Sanctified Bloodmage Robe"]=true, ["Sanctified Crimson Acolyte Raiments"]=true, ["Sanctified Dark Coven Robe"]=true },
    ["Feet"] = { ["Plague Scientist's Boots"]=true },
    ["Hands"] = { ["Bloodmage Gloves"]=true, ["Crimson Acolyte Handwraps"]=true, ["Dark Coven Gloves"]=true, ["Gunship Captain's Mittens"]=true, ["Sanctified Bloodmage Gloves"]=true, ["Sanctified Crimson Acolyte Handwraps"]=true, ["Sanctified Dark Coven Gloves"]=true },
    ["Head"] = { ["Bloodmage Hood"]=true, ["Crimson Acolyte Cowl"]=true, ["Dark Coven Hood"]=true, ["Sanctified Bloodmage Hood"]=true, ["Sanctified Crimson Acolyte Cowl"]=true, ["Sanctified Dark Coven Hood"]=true },
    ["Legs"] = { ["Bloodmage Leggings"]=true, ["Crimson Acolyte Leggings"]=true, ["Dark Coven Leggings"]=true, ["Plaguebringer's Stained Pants"]=true, ["Sanctified Bloodmage Leggings"]=true, ["Sanctified Crimson Acolyte Leggings"]=true, ["Sanctified Dark Coven Leggings"]=true },
    ["Main Hand"] = { ["Bloodsurge, Kel'Thuzad's Blade of Agony"]=true, ["Royal Scepter of Terenas II"]=true },
    ["Neck"] = { ["Amulet of the Silent Eulogy"]=true, ["Blood Queen's Crimson Choker"]=true },
    ["Off Hand"] = { ["Shadow Silk Spindle"]=true },
    ["Ring"] = { ["Ashen Band of Endless Destruction"]=true, ["Loop of the Endless Labyrinth"]=true, ["Ring of Rapid Ascent"]=true, ["Valanar's Other Signet Ring"]=true },
    ["Shoulder"] = { ["Bloodmage Shoulderpads"]=true, ["Crimson Acolyte Mantle"]=true, ["Dark Coven Shoulderpads"]=true, ["Sanctified Bloodmage Shoulderpads"]=true, ["Sanctified Crimson Acolyte Mantle"]=true, ["Sanctified Dark Coven Shoulderpads"]=true },
    ["Trinket"] = { ["Charred Twilight Scale"]=true, ["Phylactery of the Nameless Lich"]=true },
    ["Waist"] = { ["Crushing Coldwraith Belt"]=true },
    ["Wrist"] = { ["Bracers of Fiery Night"]=true },
  },
  ["Cloth Caster — Haste"] = {
    ["Back"] = { ["Cloak of Burning Dusk"]=true },
    ["Chest"] = { ["Bloodmage Robe"]=true, ["Dark Coven Robe"]=true, ["Sanctified Bloodmage Robe"]=true, ["Sanctified Dark Coven Robe"]=true },
    ["Feet"] = { ["Plague Scientist's Boots"]=true },
    ["Hands"] = { ["Bloodmage Gloves"]=true, ["Dark Coven Gloves"]=true, ["San'layn Ritualist Gloves"]=true, ["Sanctified Bloodmage Gloves"]=true, ["Sanctified Dark Coven Gloves"]=true },
    ["Head"] = { ["Bloodmage Hood"]=true, ["Dark Coven Hood"]=true, ["Sanctified Bloodmage Hood"]=true, ["Sanctified Dark Coven Hood"]=true },
    ["Legs"] = { ["Bloodmage Leggings"]=true, ["Dark Coven Leggings"]=true, ["Plaguebringer's Stained Pants"]=true, ["Sanctified Bloodmage Leggings"]=true, ["Sanctified Dark Coven Leggings"]=true },
    ["Main Hand"] = { ["Bloodsurge, Kel'Thuzad's Blade of Agony"]=true },
    ["Neck"] = { ["Amulet of the Silent Eulogy"]=true, ["Blood Queen's Crimson Choker"]=true },
    ["Off Hand"] = { ["Shadow Silk Spindle"]=true },
    ["Ring"] = { ["Ashen Band of Endless Destruction"]=true, ["Ring of Rapid Ascent"]=true },
    ["Shoulder"] = { ["Bloodmage Shoulderpads"]=true, ["Dark Coven Shoulderpads"]=true, ["Sanctified Bloodmage Shoulderpads"]=true, ["Sanctified Dark Coven Shoulderpads"]=true },
    ["Trinket"] = { ["Charred Twilight Scale"]=true, ["Dislodged Foreign Object"]=true },
    ["Waist"] = { ["Crushing Coldwraith Belt"]=true },
    ["Wrist"] = { ["Bracers of Fiery Night"]=true },
  },
  ["Healer — Haste"] = {
    ["Back"] = { ["Cloak of Burning Dusk"]=true },
    ["Chest"] = { ["Frost Witch's Tunic"]=true, ["Sanctified Frost Witch's Tunic"]=true },
    ["Feet"] = { ["Plague Scientist's Boots"]=true },
    ["Hands"] = { ["Frost Witch's Handguards"]=true, ["Sanctified Frost Witch's Handguards"]=true, ["Unclean Surgical Gloves"]=true },
    ["Head"] = { ["Frost Witch's Headpiece"]=true, ["Sanctified Frost Witch's Headpiece"]=true },
    ["Legs"] = { ["Frost Witch's Legguards"]=true, ["Sanctified Frost Witch's Legguards"]=true },
    ["Main Hand"] = { ["Royal Scepter of Terenas II"]=true },
    ["Neck"] = { ["Blood Queen's Crimson Choker"]=true },
    ["Off Hand"] = { ["Bulwark of Smouldering Steel"]=true },
    ["Ranged"] = { ["Totem of the Surging Sea"]=true },
    ["Ring"] = { ["Ashen Band of Endless Wisdom"]=true, ["Ring of Phased Regeneration"]=true },
    ["Shoulder"] = { ["Frost Witch's Spaulders"]=true, ["Sanctified Frost Witch's Spaulders"]=true },
    ["Trinket"] = { ["Glowing Twilight Scale"]=true, ["Solace of the Defeated"]=true },
    ["Waist"] = { ["Split Shape Belt"]=true },
    ["Wrist"] = { ["Bracers of Fiery Night"]=true },
  },
  ["Healer — Intellect"] = {
    ["Back"] = { ["Cloak of Burning Dusk"]=true },
    ["Chest"] = { ["Lightsworn Tunic"]=true, ["Rot-Resistant Breastplate"]=true, ["Sanctified Lightsworn Tunic"]=true },
    ["Feet"] = { ["Foreshadow Steps"]=true },
    ["Hands"] = { ["Fallen Lord's Handguards"]=true, ["Lightsworn Gloves"]=true, ["Sanctified Lightsworn Gloves"]=true },
    ["Head"] = { ["Lightsworn Headpiece"]=true, ["Sanctified Lightsworn Headpiece"]=true },
    ["Legs"] = { ["Corrupted Silverplate Leggings"]=true, ["Lightsworn Leggings"]=true, ["Sanctified Lightsworn Leggings"]=true },
    ["Main Hand"] = { ["Bloodsurge, Kel'Thuzad's Blade of Agony"]=true },
    ["Neck"] = { ["Blood Queen's Crimson Choker"]=true },
    ["Off Hand"] = { ["Bulwark of Smouldering Steel"]=true },
    ["Ranged"] = { ["Libram of Renewal"]=true },
    ["Ring"] = { ["Ashen Band of Endless Wisdom"]=true, ["Ring of Rapid Ascent"]=true },
    ["Shoulder"] = { ["Lightsworn Spaulders"]=true, ["Sanctified Lightsworn Spaulders"]=true },
    ["Trinket"] = { ["Glowing Twilight Scale"]=true, ["Talisman of Resurgence"]=true },
    ["Waist"] = { ["Split Shape Belt"]=true },
    ["Wrist"] = { ["Bracers of Fiery Night"]=true },
  },
  ["Healer — Spell Power"] = {
    ["Back"] = { ["Cloak of Burning Dusk"]=true, ["Greatcloak of the Turned Champion"]=true },
    ["Chest"] = { ["Crimson Acolyte Robe"]=true, ["Lasherweave Robes"]=true, ["Sanctified Crimson Acolyte Robe"]=true, ["Sanctified Lasherweave Robes"]=true, ["Sanguine Silk Robes"]=true },
    ["Feet"] = { ["Boots of Unnatural Growth"]=true, ["Plague Scientist's Boots"]=true },
    ["Hands"] = { ["Crimson Acolyte Gloves"]=true, ["Lasherweave Gauntlets"]=true, ["Sanctified Crimson Acolyte Gloves"]=true, ["Sanctified Lasherweave Gauntlets"]=true },
    ["Head"] = { ["Crimson Acolyte Hood"]=true, ["Lasherweave Helmet"]=true, ["Sanctified Crimson Acolyte Hood"]=true, ["Sanctified Lasherweave Helmet"]=true },
    ["Legs"] = { ["Crimson Acolyte Leggings"]=true, ["Lasherweave Legplates"]=true, ["Leggings of the Refracted Mind"]=true, ["Sanctified Crimson Acolyte Leggings"]=true, ["Sanctified Lasherweave Legplates"]=true },
    ["Main Hand"] = { ["Royal Scepter of Terenas II"]=true },
    ["Neck"] = { ["Blood Queen's Crimson Choker"]=true, ["Bone Sentinel's Amulet"]=true },
    ["Off Hand"] = { ["Shadow Silk Spindle"]=true, ["Sundial of Eternal Dusk"]=true },
    ["Ranged"] = { ["Idol of the Black Willow"]=true },
    ["Ring"] = { ["Ashen Band of Endless Wisdom"]=true, ["Memory of Malygos"]=true, ["Ring of Maddening Whispers"]=true },
    ["Shoulder"] = { ["Crimson Acolyte Shoulderpads"]=true, ["Lasherweave Pauldrons"]=true, ["Sanctified Crimson Acolyte Shoulderpads"]=true, ["Sanctified Lasherweave Pauldrons"]=true },
    ["Trinket"] = { ["Althor's Abacus"]=true, ["Glowing Twilight Scale"]=true, ["Solace of the Defeated"]=true },
    ["Waist"] = { ["Lingering Illness"]=true, ["Professor's Bloodied Smock"]=true },
    ["Wrist"] = { ["Bracers of Fiery Night"]=true },
  },
  ["Leather Armor Pen"] = {
    ["Back"] = { ["Shadowvault Slayer's Cloak"]=true, ["Sylvanas' Cunning"]=true },
    ["Chest"] = { ["Ikfirus's Sack of Wonder"]=true, ["Lasherweave Raiment"]=true, ["Sanctified Lasherweave Raiment"]=true, ["Sanctified Shadowblade Breastplate"]=true, ["Shadowblade Breastplate"]=true },
    ["Feet"] = { ["Frostbitten Fur Boots"]=true },
    ["Hands"] = { ["Aldriana's Gloves of Secrecy"]=true, ["Lasherweave Handgrips"]=true, ["Sanctified Lasherweave Handgrips"]=true, ["Sanctified Shadowblade Gauntlets"]=true, ["Shadowblade Gauntlets"]=true },
    ["Head"] = { ["Lasherweave Headguard"]=true, ["Sanctified Lasherweave Headguard"]=true, ["Sanctified Shadowblade Helmet"]=true, ["Shadowblade Helmet"]=true },
    ["Legs"] = { ["Gangrenous Leggings"]=true, ["Lasherweave Legguards"]=true, ["Sanctified Lasherweave Legguards"]=true, ["Sanctified Shadowblade Legplates"]=true, ["Shadowblade Legplates"]=true },
    ["Main Hand"] = { ["Havoc's Call, Blade of Lordaeron Kings"]=true, ["Lungbreaker"]=true, ["Oathbinder, Charge of the Ranger-General"]=true },
    ["Neck"] = { ["Sindragosa's Cruel Claw"]=true },
    ["Off Hand"] = { ["Heaven's Fall, Kryss of a Thousand Lies"]=true, ["Scourgeborne Waraxe"]=true },
    ["Ranged"] = { ["Idol of the Crying Moon"]=true },
    ["Ring"] = { ["Ashen Band of Endless Vengeance"]=true, ["Band of the Bone Colossus"]=true, ["Frostbrood Sapphire Ring"]=true, ["Signet of Twilight"]=true },
    ["Shoulder"] = { ["Lasherweave Shoulderpads"]=true, ["Sanctified Lasherweave Shoulderpads"]=true, ["Sanctified Shadowblade Pauldrons"]=true, ["Shadowblade Pauldrons"]=true },
    ["Trinket"] = { ["Deathbringer's Will"]=true, ["Sharpened Twilight Scale"]=true, ["Tiny Abomination in a Jar"]=true },
    ["Waist"] = { ["Astrylian's Sutured Cinch"]=true },
    ["Wrist"] = { ["Toskk's Maximized Wristguards"]=true, ["Umbrage Armbands"]=true },
  },
  ["Leather Caster"] = {
    ["Back"] = { ["Cloak of Burning Dusk"]=true },
    ["Chest"] = { ["Lasherweave Vestment"]=true, ["Sanctified Lasherweave Vestment"]=true },
    ["Feet"] = { ["Plague Scientist's Boots"]=true },
    ["Hands"] = { ["Lasherweave Gloves"]=true, ["Sanctified Lasherweave Gloves"]=true },
    ["Head"] = { ["Lasherweave Cover"]=true, ["Sanctified Lasherweave Cover"]=true },
    ["Legs"] = { ["Lasherweave Trousers"]=true, ["Sanctified Lasherweave Trousers"]=true },
    ["Main Hand"] = { ["Royal Scepter of Terenas II"]=true },
    ["Neck"] = { ["Blood Queen's Crimson Choker"]=true },
    ["Off Hand"] = { ["Shadow Silk Spindle"]=true },
    ["Ranged"] = { ["Idol of the Lunar Eclipse"]=true },
    ["Ring"] = { ["Ashen Band of Endless Destruction"]=true, ["Ring of Rapid Ascent"]=true },
    ["Shoulder"] = { ["Lasherweave Mantle"]=true, ["Sanctified Lasherweave Mantle"]=true },
    ["Trinket"] = { ["Charred Twilight Scale"]=true, ["Phylactery of the Nameless Lich"]=true },
    ["Waist"] = { ["Crushing Coldwraith Belt"]=true },
    ["Wrist"] = { ["Bracers of Fiery Night"]=true },
  },
  ["Leather Tank"] = {
    ["Back"] = { ["Sentinel's Winter Cloak"]=true },
    ["Chest"] = { ["Chestguard of the Frigid Noose"]=true, ["Lasherweave Raiment"]=true, ["Sanctified Lasherweave Raiment"]=true },
    ["Feet"] = { ["Frostbitten Fur Boots"]=true },
    ["Hands"] = { ["Lasherweave Handgrips"]=true, ["Sanctified Lasherweave Handgrips"]=true },
    ["Head"] = { ["Lasherweave Headguard"]=true, ["Sanctified Lasherweave Headguard"]=true },
    ["Legs"] = { ["Lasherweave Legguards"]=true, ["Sanctified Lasherweave Legguards"]=true },
    ["Main Hand"] = { ["Oathbinder, Charge of the Ranger-General"]=true },
    ["Neck"] = { ["Bile-Encrusted Medallion"]=true },
    ["Ranged"] = { ["Idol of the Crying Moon"]=true },
    ["Ring"] = { ["Ashen Band of Endless Courage"]=true, ["Devium's Eternally Cold Ring"]=true },
    ["Shoulder"] = { ["Lasherweave Shoulderpads"]=true, ["Sanctified Lasherweave Shoulderpads"]=true },
    ["Trinket"] = { ["Juggernaut's Vitality"]=true, ["Sindragosa's Flawless Fang"]=true },
    ["Waist"] = { ["Astrylian's Sutured Cinch"]=true },
    ["Wrist"] = { ["Toskk's Maximized Wristguards"]=true },
  },
  ["Mail Armor Pen"] = {
    ["Back"] = { ["Sylvanas' Cunning"]=true },
    ["Chest"] = { ["Ahn'Kahar Blood Hunter's Tunic"]=true, ["Sanctified Ahn'Kahar Blood Hunter's Tunic"]=true },
    ["Feet"] = { ["Returning Footfalls"]=true },
    ["Hands"] = { ["Ahn'Kahar Blood Hunter's Handguards"]=true, ["Sanctified Ahn'Kahar Blood Hunter's Handguards"]=true },
    ["Head"] = { ["Ahn'Kahar Blood Hunter's Headpiece"]=true, ["Sanctified Ahn'Kahar Blood Hunter's Headpiece"]=true },
    ["Legs"] = { ["Ahn'Kahar Blood Hunter's Legguards"]=true, ["Leggings of Northern Lights"]=true, ["Sanctified Ahn'Kahar Blood Hunter's Legguards"]=true },
    ["Main Hand"] = { ["Oathbinder, Charge of the Ranger-General"]=true },
    ["Neck"] = { ["Sindragosa's Cruel Claw"]=true },
    ["Ring"] = { ["Ashen Band of Endless Vengeance"]=true, ["Frostbrood Sapphire Ring"]=true },
    ["Shoulder"] = { ["Ahn'Kahar Blood Hunter's Spaulders"]=true, ["Sanctified Ahn'Kahar Blood Hunter's Spaulders"]=true },
    ["Trinket"] = { ["Deathbringer's Will"]=true, ["Sharpened Twilight Scale"]=true },
    ["Waist"] = { ["Nerub'ar Stalker's Cord"]=true },
    ["Wrist"] = { ["Scourge Hunter's Vambraces"]=true },
  },
  ["Mail Caster"] = {
    ["Back"] = { ["Cloak of Burning Dusk"]=true },
    ["Chest"] = { ["Frost Witch's Hauberk"]=true, ["Sanctified Frost Witch's Hauberk"]=true },
    ["Feet"] = { ["Plague Scientist's Boots"]=true },
    ["Hands"] = { ["Frost Witch's Gloves"]=true, ["Sanctified Frost Witch's Gloves"]=true },
    ["Head"] = { ["Frost Witch's Helm"]=true, ["Sanctified Frost Witch's Helm"]=true },
    ["Legs"] = { ["Frost Witch's Kilt"]=true, ["Sanctified Frost Witch's Kilt"]=true },
    ["Main Hand"] = { ["Royal Scepter of Terenas II"]=true },
    ["Neck"] = { ["Blood Queen's Crimson Choker"]=true },
    ["Off Hand"] = { ["Bulwark of Smouldering Steel"]=true },
    ["Ranged"] = { ["Totem of the Surging Sea"]=true },
    ["Ring"] = { ["Ashen Band of Endless Destruction"]=true, ["Ring of Rapid Ascent"]=true },
    ["Shoulder"] = { ["Frost Witch's Shoulderpads"]=true, ["Sanctified Frost Witch's Shoulderpads"]=true },
    ["Trinket"] = { ["Charred Twilight Scale"]=true, ["Sindragosa's Flawless Fang"]=true },
    ["Waist"] = { ["Split Shape Belt"]=true },
    ["Wrist"] = { ["Bracers of Fiery Night"]=true },
  },
  ["Plate Armor Pen"] = {
    ["Back"] = { ["Sylvanas' Cunning"]=true, ["Winding Sheet"]=true },
    ["Chest"] = { ["Sanctified Scourgelord Battleplate"]=true, ["Sanctified Ymirjar Lord's Battleplate"]=true, ["Scourgelord Battleplate"]=true, ["Ymirjar Lord's Battleplate"]=true },
    ["Feet"] = { ["Apocalypse's Advance"]=true },
    ["Hands"] = { ["Aldriana's Gloves of Secrecy"]=true, ["Sanctified Scourgelord Gauntlets"]=true, ["Sanctified Ymirjar Lord's Gauntlets"]=true, ["Scourgelord Gauntlets"]=true, ["Ymirjar Lord's Gauntlets"]=true },
    ["Head"] = { ["Sanctified Scourgelord Helmet"]=true, ["Sanctified Ymirjar Lord's Helmet"]=true, ["Scourgelord Helmet"]=true, ["Ymirjar Lord's Helmet"]=true },
    ["Legs"] = { ["Sanctified Scourgelord Legplates"]=true, ["Sanctified Ymirjar Lord's Legplates"]=true, ["Scourgelord Legplates"]=true, ["Ymirjar Lord's Legplates"]=true },
    ["Main Hand"] = { ["Havoc's Call, Blade of Lordaeron Kings"]=true, ["Shadow's Edge"]=true, ["Shadowmourne"]=true },
    ["Neck"] = { ["Penumbra Pendant"]=true },
    ["Off Hand"] = { ["Glorenzelg, High-Blade of the Silver Hand"]=true, ["Havoc's Call, Blade of Lordaeron Kings"]=true, ["Shadow's Edge"]=true },
    ["Ranged"] = { ["Sigil of Awareness"]=true },
    ["Ring"] = { ["Ashen Band of Endless Might"]=true, ["Ashen Band of Endless Vengeance"]=true, ["Frostbrood Sapphire Ring"]=true, ["Might of Blight"]=true },
    ["Wrist"] = { ["Bracers of Dark Reckoning"]=true },
    ["Shoulder"] = { ["Sanctified Scourgelord Shoulderplates"]=true, ["Sanctified Ymirjar Lord's Shoulderplates"]=true, ["Scourgelord Shoulderplates"]=true, ["Ymirjar Lord's Shoulderplates"]=true },
    ["Trinket"] = { ["Deathbringer's Will"]=true, ["Sharpened Twilight Scale"]=true },
    ["Waist"] = { ["Coldwraith Links"]=true },
  },
  ["Plate Strength"] = {
    ["Back"] = { ["Shadowvault Slayer's Cloak"]=true, ["Winding Sheet"]=true },
    ["Chest"] = { ["Lightsworn Battleplate"]=true, ["Sanctified Lightsworn Battleplate"]=true, ["Sanctified Scourgelord Battleplate"]=true, ["Scourgelord Battleplate"]=true },
    ["Feet"] = { ["Apocalypse's Advance"]=true },
    ["Hands"] = { ["Anub'ar Stalker's Gloves"]=true, ["Lightsworn Gauntlets"]=true, ["Sanctified Lightsworn Gauntlets"]=true, ["Sanctified Scourgelord Gauntlets"]=true, ["Scourgelord Gauntlets"]=true },
    ["Head"] = { ["Lightsworn Helmet"]=true, ["Sanctified Lightsworn Helmet"]=true, ["Sanctified Scourgelord Helmet"]=true, ["Scourgelord Helmet"]=true },
    ["Legs"] = { ["Lightsworn Legplates"]=true, ["Sanctified Lightsworn Legplates"]=true, ["Sanctified Scourgelord Legplates"]=true, ["Scourge Reaver's Legplates"]=true, ["Scourgelord Legplates"]=true },
    ["Main Hand"] = { ["Shadow's Edge"]=true, ["Shadowmourne"]=true },
    ["Neck"] = { ["Penumbra Pendant"]=true },
    ["Ranged"] = { ["Libram of Three Truths"]=true, ["Sigil of the Hanged Man"]=true },
    ["Ring"] = { ["Ashen Band of Endless Might"]=true, ["Might of Blight"]=true, ["Signet of Twilight"]=true },
    ["Wrist"] = { ["Bracers of Dark Reckoning"]=true },
    ["Shoulder"] = { ["Lightsworn Shoulderplates"]=true, ["Sanctified Lightsworn Shoulderplates"]=true, ["Sanctified Scourgelord Shoulderplates"]=true, ["Scourgelord Shoulderplates"]=true },
    ["Trinket"] = { ["Deathbringer's Will"]=true, ["Sharpened Twilight Scale"]=true, ["Tiny Abomination in a Jar"]=true },
    ["Waist"] = { ["Astrylian's Sutured Cinch"]=true, ["Coldwraith Links"]=true },
  },
  ["Plate Tank"] = {
    ["Back"] = { ["Royal Crimson Cloak"]=true },
    ["Chest"] = { ["Lightsworn Chestguard"]=true, ["Sanctified Lightsworn Chestguard"]=true, ["Sanctified Scourgelord Chestguard"]=true, ["Sanctified Ymirjar Lord's Plate"]=true, ["Scourgelord Chestguard"]=true, ["Ymirjar Lord's Plate"]=true },
    ["Feet"] = { ["Grinning Skull Greatboots"]=true, ["Treads of Impending Resurrection"]=true },
    ["Hands"] = { ["Lightsworn Handguards"]=true, ["Sanctified Lightsworn Handguards"]=true, ["Sanctified Scourgelord Handguards"]=true, ["Sanctified Ymirjar Lord's Handguards"]=true, ["Scourgelord Handguards"]=true, ["Ymirjar Lord's Handguards"]=true },
    ["Head"] = { ["Broken Ram Skull Helm"]=true, ["Lightsworn Faceguard"]=true, ["Sanctified Lightsworn Faceguard"]=true, ["Sanctified Scourgelord Faceguard"]=true, ["Sanctified Ymirjar Lord's Greathelm"]=true, ["Scourgelord Faceguard"]=true, ["Ymirjar Lord's Greathelm"]=true },
    ["Legs"] = { ["Lightsworn Legguards"]=true, ["Sanctified Lightsworn Legguards"]=true, ["Sanctified Scourgelord Legguards"]=true, ["Sanctified Ymirjar Lord's Legguards"]=true, ["Scourgelord Legguards"]=true, ["Ymirjar Lord's Legguards"]=true },
    ["Main Hand"] = { ["Glorenzelg, High-Blade of the Silver Hand"]=true, ["Havoc's Call, Blade of Lordaeron Kings"]=true, ["Mithrios, Bronzebeard's Legacy"]=true },
    ["Neck"] = { ["Bile-Encrusted Medallion"]=true, ["Noose of Malachite"]=true },
    ["Off Hand"] = { ["Icecrown Glacial Wall"]=true },
    ["Ranged"] = { ["Dreamhunter's Carbine"]=true, ["Libram of the Sacred Shield"]=true, ["Sigil of the Frozen Conscience"]=true },
    ["Ring"] = { ["Ashen Band of Endless Courage"]=true, ["Devium's Eternally Cold Ring"]=true, ["Juggernaut Band"]=true, ["Signified Ring of Binding"]=true },
    ["Shoulder"] = { ["Lightsworn Shoulderguards"]=true, ["Sanctified Lightsworn Shoulderguards"]=true, ["Sanctified Scourgelord Pauldrons"]=true, ["Sanctified Ymirjar Lord's Pauldrons"]=true, ["Scourgelord Pauldrons"]=true, ["Ymirjar Lord's Pauldrons"]=true },
    ["Trinket"] = { ["Petrified Twilight Scale"]=true, ["Sindragosa's Flawless Fang"]=true, ["Unidentifiable Organ"]=true },
    ["Waist"] = { ["Belt of Broken Bones"]=true, ["Verdigris Chain Belt"]=true },
    ["Wrist"] = { ["Bracers of Dark Reckoning"]=true, ["Gargoyle Spit Bracers"]=true },
  },
}
